/**
 * Cross-validation tests: compare TS inference results against Java reference engine.
 * Reference values were generated by running com.ochafik.math.bayes.InferenceTest
 * on the dog-problem network with the original Java JunctionTreeAlgorithmUtils.
 */
import { describe, it, expect } from 'vitest';
import { BayesianNetwork } from '../src/lib/network.js';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { JSDOM } from 'jsdom';

const dogProblemXml = readFileSync(resolve(__dirname, '../src/example.xmlbif'), 'utf-8');
const domParser = {
  parseFromString: (s: string, t: string) => new JSDOM(s, { contentType: t }).window.document,
};

function loadNet() {
  return BayesianNetwork.fromXmlBif(dogProblemXml, domParser);
}

function getPosterior(net: BayesianNetwork, evidence?: Map<string, string>) {
  const result = net.infer(evidence);
  const posteriors: Record<string, Record<string, number>> = {};
  for (const v of net.variables) {
    const dist = result.posteriors.get(v);
    if (dist) {
      posteriors[v.name] = Object.fromEntries(dist);
    }
  }
  return posteriors;
}

// Java reference values (6 decimal places from InferenceTest.java)
const JAVA_PRIORS = {
  'light-on':       { true: 0.132500, false: 0.867500 },
  'hear-bark':      { true: 0.283123, false: 0.716877 },
  'bowel-problem':  { true: 0.010000, false: 0.990000 },
  'dog-out':        { true: 0.395830, false: 0.604170 },
  'family-out':     { true: 0.150000, false: 0.850000 },
};

const JAVA_HEAR_BARK_TRUE = {
  'light-on':       { true: 0.234050, false: 0.765950 },
  'hear-bark':      { true: 1.000000, false: 0.000000 },
  'bowel-problem':  { true: 0.024066, false: 0.975934 },
  'dog-out':        { true: 0.978660, false: 0.021340 },
  'family-out':     { true: 0.334636, false: 0.665364 },
};

const JAVA_DOG_OUT_FALSE = {
  'light-on':       { true: 0.063532, false: 0.936468 },
  'hear-bark':      { true: 0.010000, false: 0.990000 },
  'bowel-problem':  { true: 0.000447, false: 0.999553 },
  'dog-out':        { true: 0.000000, false: 1.000000 },
  'family-out':     { true: 0.024604, false: 0.975396 },
};

const JAVA_FAMILY_OUT_TRUE = {
  'light-on':       { true: 0.600000, false: 0.400000 },
  'hear-bark':      { true: 0.631621, false: 0.368379 },
  'bowel-problem':  { true: 0.010000, false: 0.990000 },
  'dog-out':        { true: 0.900900, false: 0.099100 },
  'family-out':     { true: 1.000000, false: 0.000000 },
};

// Note: Java uses underscores (dog_out), TS uses hyphens (dog-out) from XMLBIF
function compareWithJava(
  tsResult: Record<string, Record<string, number>>,
  javaRef: Record<string, Record<string, number>>,
  tolerance: number,
  label: string,
) {
  for (const [javaName, javaDist] of Object.entries(javaRef)) {
    // Java uses dog_out, TS XMLBIF has dog-out
    const tsName = javaName.replace(/_/g, '-');
    const tsDist = tsResult[tsName];
    expect(tsDist, `Missing variable ${tsName} in TS result for ${label}`).toBeDefined();
    for (const [outcome, javaProb] of Object.entries(javaDist)) {
      const tsProb = tsDist[outcome];
      expect(tsProb, `Missing outcome ${outcome} for ${tsName}`).toBeDefined();
      expect(tsProb).toBeCloseTo(javaProb, tolerance);
    }
  }
}

describe('Cross-validation with Java engine', () => {
  it('priors match Java reference', () => {
    const net = loadNet();
    const posteriors = getPosterior(net);
    compareWithJava(posteriors, JAVA_PRIORS, 3, 'priors');
  });

  it('hear-bark=true posteriors match Java reference', () => {
    const net = loadNet();
    const evidence = new Map([['hear-bark', 'true']]);
    const posteriors = getPosterior(net, evidence);
    compareWithJava(posteriors, JAVA_HEAR_BARK_TRUE, 3, 'hear-bark=true');
  });

  it('dog-out=false posteriors match Java reference', () => {
    const net = loadNet();
    const evidence = new Map([['dog-out', 'false']]);
    const posteriors = getPosterior(net, evidence);
    compareWithJava(posteriors, JAVA_DOG_OUT_FALSE, 3, 'dog-out=false');
  });

  it('family-out=true posteriors match Java reference', () => {
    const net = loadNet();
    const evidence = new Map([['family-out', 'true']]);
    const posteriors = getPosterior(net, evidence);
    compareWithJava(posteriors, JAVA_FAMILY_OUT_TRUE, 3, 'family-out=true');
  });
});
